/* Solar Cartography utility-scale station: a navy-and-lime field instrument that turns site-scale solar inputs into transparent planning outputs. */
import { useMemo, useState } from "react";
import { ArrowLeft, ArrowUpRight, BarChart3, Building2, Download, Factory, MapPin, RefreshCw, ShieldCheck, SunMedium, Zap } from "lucide-react";
import { Bar, BarChart, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const logoUrl = "/manus-storage/xtorra-logo_6cfa4db6.png";
const number = (value: number, digits = 0) => new Intl.NumberFormat("en-US", { maximumFractionDigits: digits, minimumFractionDigits: digits }).format(Number.isFinite(value) ? value : 0);

function InputField({ label, note, value, onChange, min = 0, step = 1, suffix }: { label: string; note: string; value: number; onChange: (next: number) => void; min?: number; step?: number; suffix: string }) {
  return <label className="block text-[0.65rem] font-extrabold uppercase tracking-[0.12em] text-[#345E7D]">{label}<span className="mt-1 block normal-case text-xs font-medium tracking-normal text-[#7891A1]">{note}</span><div className="mt-2 flex items-center border-b border-[#B8C7D4] bg-white"><input type="number" min={min} step={step} value={value} onChange={(event) => onChange(Number(event.target.value))} className="h-10 min-w-0 flex-1 bg-transparent px-0 text-base font-extrabold text-[#082C67] outline-none" /><span className="pl-3 text-xs font-bold text-[#638093]">{suffix}</span></div></label>;
}

export default function UtilityScale() {
  const [siteLabel, setSiteLabel] = useState("Lagos Solar Hub, Nigeria");
  const [latitude, setLatitude] = useState(6.5244);
  const [longitude, setLongitude] = useState(3.3792);
  const [peakSunHours, setPeakSunHours] = useState(5);
  const [acMw, setAcMw] = useState(50);
  const [dcAcRatio, setDcAcRatio] = useState(1.3);
  const [moduleWp, setModuleWp] = useState(700);
  const [modulesPerString, setModulesPerString] = useState(28);
  const [inverterBlockMw, setInverterBlockMw] = useState(3.125);
  const [dcLosses, setDcLosses] = useState(14);
  const [availability, setAvailability] = useState(98);
  const [acresPerMw, setAcresPerMw] = useState(6);
  const [lookupState, setLookupState] = useState<"idle" | "loading" | "success" | "error">("idle");

  const metrics = useMemo(() => {
    const safeAcMw = Math.max(0, acMw);
    const safeRatio = Math.max(0.1, dcAcRatio);
    const safePsh = Math.max(0, peakSunHours);
    const safeModuleWp = Math.max(1, moduleWp);
    const safeBlock = Math.max(0.1, inverterBlockMw);
    const performanceRatio = Math.max(0, 1 - Math.min(100, Math.max(0, dcLosses)) / 100) * Math.min(1, Math.max(0, availability) / 100);
    const dcMw = safeAcMw * safeRatio;
    const moduleCount = Math.ceil((dcMw * 1_000_000) / safeModuleWp);
    const strings = Math.ceil(moduleCount / Math.max(1, modulesPerString));
    const inverterBlocks = Math.ceil(safeAcMw / safeBlock);
    const grossMwh = dcMw * safePsh * 365;
    const netMwh = grossMwh * performanceRatio;
    const annualCapacityFactor = safeAcMw > 0 ? (netMwh / (safeAcMw * 8760)) * 100 : 0;
    const acres = safeAcMw * Math.max(0, acresPerMw);
    return { performanceRatio, dcMw, moduleCount, strings, inverterBlocks, grossMwh, netMwh, annualCapacityFactor, acres, hectares: acres * 0.404686 };
  }, [acMw, dcAcRatio, peakSunHours, moduleWp, modulesPerString, inverterBlockMw, dcLosses, availability, acresPerMw]);

  const yieldData = [
    { name: "Gross DC", value: metrics.grossMwh / 1000, fill: "#0F6693" },
    { name: "Loss stack", value: Math.max(0, (metrics.grossMwh - metrics.netMwh) / 1000), fill: "#C4923F" },
    { name: "Net export", value: metrics.netMwh / 1000, fill: "#58A90E" },
  ];

  const lookupSolarResource = async () => {
    setLookupState("loading");
    try {
      const query = new URLSearchParams({ parameters: "ALLSKY_SFC_SW_DWN", community: "RE", longitude: String(longitude), latitude: String(latitude), start: "20250101", end: "20251231", format: "JSON" });
      const response = await fetch(`https://power.larc.nasa.gov/api/temporal/daily/point?${query.toString()}`);
      if (!response.ok) throw new Error("Solar resource lookup failed");
      const data = await response.json();
      const values = Object.values(data?.properties?.parameter?.ALLSKY_SFC_SW_DWN ?? {}).map(Number).filter((value) => Number.isFinite(value) && value > 0);
      if (!values.length) throw new Error("No usable irradiance values");
      setPeakSunHours(Number((values.reduce((sum, value) => sum + value, 0) / values.length).toFixed(2)));
      setLookupState("success");
    } catch {
      setLookupState("error");
    }
  };

  return <main className="relative min-h-screen overflow-hidden bg-[#F2F6F3] text-[#082C67]">
    <div className="pointer-events-none absolute left-0 top-[21rem] hidden h-[74rem] w-28 xl:block" aria-hidden="true"><svg viewBox="0 0 110 1180" className="h-full w-full" fill="none" preserveAspectRatio="none"><path d="M6 12C94 90 12 170 86 254C104 274 80 318 22 364C-5 385 16 465 85 540C108 565 77 625 18 680C-3 699 30 820 86 900C99 920 74 1005 20 1060" stroke="#0F6693" strokeOpacity=".16" /><path d="M18 45C82 106 22 190 74 250C106 288 67 345 29 386" stroke="#58A90E" strokeOpacity=".52" strokeDasharray="4 11" /><circle cx="29" cy="386" r="5" fill="#58A90E" /><circle cx="85" cy="540" r="3" fill="#0F6693" /></svg></div>
    <header className="relative z-10 border-b border-[#D6E2DB] bg-[#FCFCF8]"><div className="container flex min-h-24 items-center justify-between gap-5"><a href="/" className="flex items-center gap-4"><img src={logoUrl} alt="Xtorra Renewables" className="h-14 w-auto sm:h-16" /><span className="hidden border-l border-[#D6E2DB] pl-4 text-[0.62rem] font-extrabold uppercase tracking-[0.14em] text-[#54758A] sm:block">Utility-scale station / 06</span></a><a href="/" className="inline-flex items-center gap-2 text-xs font-extrabold uppercase tracking-[0.12em] text-[#244F72] hover:text-[#3F7D0C]"><ArrowLeft className="h-4 w-4" />Back to field guide</a></div></header>

    <section className="relative overflow-hidden border-b border-[#D6E2DB] bg-[#082C67] py-16 text-white sm:py-20"><div className="pointer-events-none absolute -right-10 -top-32 h-96 w-96 rounded-full border border-[#CBEF7B]/20" /><div className="pointer-events-none absolute right-[12%] top-0 h-full w-px bg-gradient-to-b from-transparent via-[#58A90E]/60 to-transparent" /><div className="container relative grid gap-10 lg:grid-cols-[1.05fr_0.95fr] lg:items-end"><div><div className="flex items-center gap-3"><Factory className="h-5 w-5 text-[#CBEF7B]" /><p className="text-[0.64rem] font-extrabold uppercase tracking-[0.16em] text-[#CBEF7B]">Field station 06 / utility planning</p></div><h1 className="mt-6 max-w-3xl font-display text-5xl leading-[0.94] tracking-[-0.05em] sm:text-7xl">Plan the scale before you build the field.</h1><p className="mt-6 max-w-2xl text-base leading-8 text-[#C0D2DF]">Turn preliminary solar resource, export capacity, technology and land inputs into a transparent utility-scale planning basis for early discussions with Xtorra.</p></div><div className="border-l border-[#CBEF7B]/40 pl-6"><p className="text-[0.62rem] font-extrabold uppercase tracking-[0.14em] text-[#CBEF7B]">Output route</p><div className="mt-4 grid gap-3 text-sm text-[#D8E6EF]"><span className="flex items-center gap-3"><i className="h-px w-7 bg-[#58A90E]" />DC array and AC export</span><span className="flex items-center gap-3"><i className="h-px w-7 bg-[#58A90E]" />Annual energy and capacity factor</span><span className="flex items-center gap-3"><i className="h-px w-7 bg-[#58A90E]" />Land, modules and inverter blocks</span></div></div></div></section>

    <section className="container relative py-12 sm:py-16"><div className="pointer-events-none absolute left-10 right-10 top-6 hidden h-20 xl:block" aria-hidden="true"><svg viewBox="0 0 1180 80" className="h-full w-full" fill="none" preserveAspectRatio="none"><path d="M0 56C165 72 252 15 426 36C560 52 630 11 776 26C941 42 1034 12 1180 22" stroke="#0F6693" strokeOpacity=".15" /><path d="M0 63C170 79 253 25 430 44C576 62 638 19 780 35" stroke="#58A90E" strokeOpacity=".55" strokeDasharray="5 12" /><circle cx="780" cy="35" r="4" fill="#58A90E" /></svg></div><div className="relative grid gap-8 xl:grid-cols-[1.1fr_0.9fr]"><div className="space-y-8"><section className="relative overflow-hidden border border-[#D6E2DB] bg-white p-6 shadow-[0_18px_45px_rgba(8,44,103,0.06)] sm:p-8"><div className="pointer-events-none absolute -right-14 -top-14 h-44 w-44 rounded-full border border-[#0F6693]/12" /><div className="pointer-events-none absolute bottom-0 left-0 h-32 w-full opacity-40" aria-hidden="true"><svg viewBox="0 0 760 160" className="h-full w-full" fill="none" preserveAspectRatio="none"><path d="M-20 140C100 96 175 164 276 112C358 70 441 123 529 77C605 38 680 75 788 19" stroke="#0F6693" strokeOpacity=".12" /><path d="M-20 152C110 108 186 175 286 124C380 76 455 137 538 90" stroke="#58A90E" strokeOpacity=".18" strokeDasharray="3 8" /></svg></div><div className="relative flex flex-wrap items-start justify-between gap-5 border-b border-[#D6E2DB] pb-6"><div><div className="flex items-center gap-3"><MapPin className="h-5 w-5 text-[#58A90E]" /><p className="text-[0.63rem] font-extrabold uppercase tracking-[0.14em] text-[#54758A]">Coordinate record / 06A · editable datum</p></div><h2 className="mt-3 text-2xl font-extrabold text-[#082C67]">Site, resource, and plant assumptions</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[#638093]">Every field is editable. Start with a site label and use the solar-resource lookup as a planning input—not a bankable yield study.</p></div><span className="border border-[#B8D8A3] bg-[#E5F6BB] px-3 py-2 text-[0.6rem] font-extrabold uppercase tracking-[0.12em] text-[#3F7D0C]">Input station A</span></div>
              <div className="mt-7 grid gap-x-6 gap-y-7 sm:grid-cols-2"><label className="sm:col-span-2 block text-[0.65rem] font-extrabold uppercase tracking-[0.12em] text-[#345E7D]">Project / site label<input value={siteLabel} onChange={(event) => setSiteLabel(event.target.value)} className="mt-2 h-10 w-full border-b border-[#B8C7D4] bg-transparent px-0 text-base font-extrabold normal-case tracking-normal text-[#082C67] outline-none" /></label><InputField label="Latitude" note="decimal degrees" value={latitude} onChange={setLatitude} min={-90} step={0.0001} suffix="°" /><InputField label="Longitude" note="decimal degrees" value={longitude} onChange={setLongitude} min={-180} step={0.0001} suffix="°" /><InputField label="Peak-sun-hours" note="daily all-sky irradiance average" value={peakSunHours} onChange={setPeakSunHours} min={0} step={0.01} suffix="kWh/m²/day" /><div className="flex items-end"><button type="button" onClick={lookupSolarResource} disabled={lookupState === "loading"} className="flex h-11 w-full items-center justify-center gap-2 border border-[#0F6693] bg-[#F2F7ED] px-4 text-xs font-extrabold uppercase tracking-[0.1em] text-[#082C67] hover:bg-[#E5F6BB] disabled:opacity-60"><RefreshCw className={`h-4 w-4 text-[#3F7D0C] ${lookupState === "loading" ? "animate-spin" : ""}`} />{lookupState === "loading" ? "Reading resource" : "Look up insolation"}</button></div></div><p className={`mt-4 text-xs leading-5 ${lookupState === "error" ? "text-[#A54B36]" : "text-[#638093]"}`}>{lookupState === "success" ? "NASA POWER daily all-sky irradiance average applied to the planning field." : lookupState === "error" ? "Lookup was unavailable. Enter or retain an approved planning resource value." : "The live lookup uses NASA POWER daily all-sky surface shortwave irradiance for the supplied coordinates."}</p>
              <div className="mt-8 grid gap-x-6 gap-y-7 border-t border-[#D6E2DB] pt-7 sm:grid-cols-2"><InputField label="AC export capacity" note="planned point-of-interconnection capacity" value={acMw} onChange={setAcMw} min={0.1} step={0.1} suffix="MWac" /><InputField label="DC / AC ratio" note="nominal DC array divided by AC export" value={dcAcRatio} onChange={setDcAcRatio} min={0.1} step={0.01} suffix="×" /><InputField label="Module rating" note="selected utility-scale module nameplate" value={moduleWp} onChange={setModuleWp} min={1} step={5} suffix="Wp" /><InputField label="Modules per string" note="planning string count; validate voltage window" value={modulesPerString} onChange={setModulesPerString} min={1} step={1} suffix="modules" /><InputField label="Inverter block size" note="nominal AC power per block" value={inverterBlockMw} onChange={setInverterBlockMw} min={0.1} step={0.125} suffix="MWac" /><InputField label="DC-side losses" note="combined planning loss stack" value={dcLosses} onChange={setDcLosses} min={0} step={0.5} suffix="%" /><InputField label="Availability" note="planned operating availability" value={availability} onChange={setAvailability} min={0} step={0.5} suffix="%" /><InputField label="Land-use planning factor" note="editable early-stage footprint benchmark" value={acresPerMw} onChange={setAcresPerMw} min={0} step={0.1} suffix="acres/MWac" /></div></section>
              <section className="relative overflow-hidden border-l-2 border-[#58A90E] bg-[#EAF3E3] p-6"><div className="pointer-events-none absolute right-0 top-0 h-full w-32" aria-hidden="true"><svg viewBox="0 0 128 180" className="h-full w-full" fill="none" preserveAspectRatio="none"><path d="M0 150C35 120 53 173 86 126C104 100 111 64 138 22" stroke="#0F6693" strokeOpacity=".18" /><circle cx="86" cy="126" r="4" fill="#58A90E" /></svg></div><div className="relative flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-[#3F7D0C]" /><div><p className="text-[0.65rem] font-extrabold uppercase tracking-[0.13em] text-[#3F7D0C]">Station D / method and scope</p><p className="mt-2 text-sm leading-6 text-[#416878]">Annual generation is calculated as DC MW × peak-sun-hours/day × 365 × the editable performance factor. Land is a planning-level estimate; the starting 6 acres/MWac sits within SEIA’s published 5–7 acres/MW utility-scale range. Detailed layout, clipping, tracker geometry, grid studies, environmental reviews, geotechnical design, and energy yield modelling remain outside this page.</p></div></div></section></div>

      <aside className="space-y-6 xl:sticky xl:top-6 xl:self-start"><section className="relative overflow-hidden bg-[#082C67] p-7 text-white sm:p-8"><div className="pointer-events-none absolute -right-12 -top-12 h-56 w-56 rounded-full border border-[#CBEF7B]/20" /><div className="relative flex items-center gap-3"><SunMedium className="h-5 w-5 text-[#CBEF7B]" /><p className="text-[0.63rem] font-extrabold uppercase tracking-[0.14em] text-[#CBEF7B]">Measured output / 06B</p></div><div className="relative mt-5"><h2 className="font-display text-4xl leading-[0.96] tracking-[-0.04em]">Utility-scale sizing basis</h2><p className="mt-3 text-sm leading-6 text-[#C0D2DF]">{siteLabel || "Unlabelled site"} · {latitude.toFixed(4)}, {longitude.toFixed(4)}</p></div><div className="relative mt-8 space-y-5"><div className="border-b border-white/15 pb-5"><p className="text-xs font-bold uppercase tracking-[0.13em] text-[#B9CCDC]">Nominal DC array</p><p className="mt-2 font-display text-5xl tracking-[-0.05em] text-[#CBEF7B]">{number(metrics.dcMw, 2)} <span className="text-2xl">MWp</span></p><p className="mt-2 text-sm text-[#C0D2DF]">{number(acMw, 2)} MWac export × {number(dcAcRatio, 2)} DC/AC ratio</p></div><div className="grid grid-cols-2 gap-4 border-b border-white/15 pb-5"><div><p className="text-[0.62rem] font-bold uppercase tracking-[0.12em] text-[#B9CCDC]">Annual net energy</p><p className="mt-2 text-2xl font-extrabold text-white">{number(metrics.netMwh / 1000, 1)} GWh</p></div><div><p className="text-[0.62rem] font-bold uppercase tracking-[0.12em] text-[#B9CCDC]">Capacity factor</p><p className="mt-2 text-2xl font-extrabold text-[#CBEF7B]">{number(metrics.annualCapacityFactor, 1)}%</p></div></div><div className="grid grid-cols-2 gap-4"><div><p className="text-[0.62rem] font-bold uppercase tracking-[0.12em] text-[#B9CCDC]">Land footprint</p><p className="mt-2 text-xl font-extrabold">{number(metrics.acres, 1)} acres</p><p className="mt-1 text-xs text-[#C0D2DF]">{number(metrics.hectares, 1)} hectares</p></div><div><p className="text-[0.62rem] font-bold uppercase tracking-[0.12em] text-[#B9CCDC]">Performance factor</p><p className="mt-2 text-xl font-extrabold">{number(metrics.performanceRatio * 100, 1)}%</p><p className="mt-1 text-xs text-[#C0D2DF]">Losses × availability</p></div></div></div></section>
        <section className="relative overflow-hidden border border-[#D6E2DB] bg-white p-6 shadow-[0_18px_45px_rgba(8,44,103,0.05)]"><div className="pointer-events-none absolute right-[-36px] top-[-40px] h-40 w-40 rounded-full border border-[#0F6693]/12 shadow-[0_0_0_24px_rgba(88,169,14,0.035)]" /><div className="relative flex items-center gap-3"><SunMedium className="h-5 w-5 text-[#58A90E]" /><div><p className="text-[0.63rem] font-extrabold uppercase tracking-[0.14em] text-[#54758A]">Station B / energy route</p><h3 className="mt-2 text-xl font-extrabold text-[#082C67]">Gross to net planning energy</h3></div></div><div className="relative mt-5 h-56"><ResponsiveContainer width="100%" height="100%"><BarChart data={yieldData} margin={{ top: 8, right: 6, left: -18, bottom: 0 }}><XAxis dataKey="name" tick={{ fill: "#527087", fontSize: 11, fontWeight: 700 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: "#7891A1", fontSize: 10 }} axisLine={false} tickLine={false} unit=" GWh" /><Tooltip cursor={{ fill: "#F2F6F3" }} formatter={(value: number) => [`${number(value, 1)} GWh`, "Annual planning energy"]} /><Bar dataKey="value" radius={[3, 3, 0, 0]}>{yieldData.map((item) => <Cell key={item.name} fill={item.fill} />)}</Bar></BarChart></ResponsiveContainer></div><p className="relative mt-3 border-l-2 border-[#58A90E] pl-3 text-xs leading-5 text-[#638093]">The loss bar is the estimated gross-to-net difference from your editable loss and availability fields, not a standalone energy output.</p></section>
        <section className="relative overflow-hidden border border-[#CDE0D4] bg-[#F7FAF7] p-6"><div className="pointer-events-none absolute right-0 top-0 h-24 w-28 opacity-70" aria-hidden="true"><svg viewBox="0 0 112 96" className="h-full w-full" fill="none"><path d="M12 84A76 76 0 0 1 98 10" stroke="#0F6693" strokeOpacity=".2" /><path d="M12 84L45 53M12 84L68 32M12 84L88 16" stroke="#58A90E" strokeOpacity=".55" strokeDasharray="3 7" /><circle cx="12" cy="84" r="4" fill="#58A90E" /></svg></div><div className="relative flex items-center gap-3"><Building2 className="h-5 w-5 text-[#58A90E]" /><div><p className="text-[0.63rem] font-extrabold uppercase tracking-[0.14em] text-[#54758A]">Station C / bill of quantity basis</p><h3 className="mt-2 text-xl font-extrabold text-[#082C67]">Early equipment schedule</h3></div></div><dl className="relative mt-5 divide-y divide-[#DCE6E2] border-y border-[#DCE6E2]">{[["PV modules", `${number(metrics.moduleCount)} × ${number(moduleWp)} Wp`], ["PV strings", `${number(metrics.strings)} planning strings of ${number(modulesPerString)} modules`], ["Inverter blocks", `${number(metrics.inverterBlocks)} × ${number(inverterBlockMw, 3)} MWac`], ["AC export capacity", `${number(acMw, 2)} MWac at point of interconnection`], ["Land estimate", `${number(metrics.acres, 1)} acres / ${number(metrics.hectares, 1)} ha`], ["Resource basis", `${number(peakSunHours, 2)} peak-sun-hours/day`]].map(([label, value]) => <div key={label} className="grid grid-cols-[0.42fr_0.58fr] gap-3 py-3"><dt className="text-xs font-extrabold text-[#244F72]">{label}</dt><dd className="text-right text-xs leading-5 text-[#58758A]">{value}</dd></div>)}</dl><a href="#utility-enquiry" className="relative mt-5 flex h-11 items-center justify-center gap-2 bg-[#082C67] text-xs font-extrabold uppercase tracking-[0.1em] text-white hover:bg-[#0D3D83]">Discuss this utility route <ArrowUpRight className="h-4 w-4 text-[#CBEF7B]" /></a></section></aside></div></section>

    <section id="utility-enquiry" className="border-t border-[#D6E2DB] bg-[#EAF3E3] py-14"><div className="container grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-[0.63rem] font-extrabold uppercase tracking-[0.14em] text-[#3F7D0C]">Route terminus / utility scale</p><h2 className="mt-3 max-w-3xl font-display text-4xl leading-[0.98] tracking-[-0.04em] text-[#082C67]">Ready to move from a planning view to a site-specific development path?</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-[#56768A]">Share the site location, intended export capacity, grid-connection context, and delivery timeline with Xtorra. We will help identify the next technical, commercial, and permitting inputs.</p></div><a href="mailto:sales@xtorra.com?subject=Utility-scale%20solar%20planning%20enquiry" className="inline-flex h-12 items-center justify-center gap-2 bg-[#082C67] px-6 text-xs font-extrabold uppercase tracking-[0.1em] text-white hover:bg-[#0D3D83]">Email Xtorra sales <ArrowUpRight className="h-4 w-4 text-[#CBEF7B]" /></a></div></section>
  </main>;
}
